"""empty message

Revision ID: 43f46387d836
Revises: 6f2a89e50fa5
Create Date: 2020-12-10 17:00:08.451096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f46387d836'
down_revision = '6f2a89e50fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('test', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'test')
    # ### end Alembic commands ###
