"""empty message

Revision ID: 718f0e4a64a6
Revises: 
Create Date: 2020-12-10 10:45:42.869171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '718f0e4a64a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('num', sa.NUMERIC(precision=20, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('demo_item',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('extend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demo_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demo_id'], ['demo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_item')
    op.drop_table('demo')
    # ### end Alembic commands ###
